version: '3.8'

services:
  ws-node:
    build: .
    container_name: websocket_research
    network_mode: "host"
    devices:
      - "/dev/video3:/dev/video3"
    privileged: true
    volumes:
      - ./app:/app